### ISSUE TITLE
Not working with days starting with 0

### ISSUE THREAD

**Issue by bharrisau** [mischief/coreos-sshguard#1]
Hi,

I just tried this today (7th) and it didn't seem to detect the attempts. I've had to change the day of the month to remove the leading 0 by inserting this in the service.

```
sed -u "s/ 0\([1-9]\) / \1 /"
```

It might not be the best solution, but it is working in the interim.

**Comment by mischief** [comment]
@bharrisau would that be in addition to, or modifying the current sed pipeline?

**Comment by mischief** [comment]
@bharrisau if you can submit a PR i will accept it if it fixes the issue :-)

**Comment by bharrisau** [comment]
I've never taken the time to learn multiple sed rules in one invocation as
piping it into a new one is easier.

I assume the rule could be added to one.

If you are ok with the regexp I'll submit a PR then. I was going to see if
the newest sshguard in the alpine repo works first. From the source it
looks to support both the right date format and the pid (so no sed needed).

**Comment by mischief** [comment]
@bharrisau it should work fine with multiple expressions if you use `-e "expression" -e "expression"` in the sed invocation.

**Comment by mischief** [comment]
@bharrisau i'll investigate the newer sshguard.

**Comment by mischief** [comment]
i see that upstream sshguard 1.6.0 release announcement says:

`- - Fix log parsing on days beginning with zero`

so if i move to a newer sshguard, this will be fixed.

**Comment by bharrisau** [comment]
Did you want to put all of the Dockerfile RUN commands into one also? It
seems to be the standard way and avoids creating multiple intermediate
images to push/pull.
On 8 Oct 2015 7:37 am, "Nick Owens" notifications@github.com wrote:

i see that upstream sshguard 1.6.0 release announcement says:
- \- Fix log parsing on days beginning with zero

so if i move to a newer sshguard, this will be fixed.

**Comment by mischief** [comment]
@bharrisau i've updated the dockerfile, the fleet unit, and tagged an image on docker hub (1.6.0). let me know if you find other issues!

**Comment by bharrisau** [comment]
Just had to update the service file for the right image tag. Looks to be working, I'll keep an eye on it.
